### ISSUE TITLE
src/Data/Serialization.h fails to compile with Boost 1.58.0

### ISSUE THREAD

**Issue by jwakely** [nutjunkie/IQmol#8]
The function `boost::serialization::stl::load_collection` no longer exists, neither do `archive_input_seq` nor `no_reserve_imp`

<pre>
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h: In function ‘void boost::serialization::load(Archive&, QList<T>&, unsigned int)’:
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h:170:4: error: ‘load_collection’ is not a member of ‘boost::serialization::stl’
    boost::serialization::stl::load_collection< 
    ^
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h:171:14: error: expected primary-expression before ‘,’ token
       Archive, 
              ^
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h:172:15: error: expected primary-expression before ‘,’ token
       QList<U>, 
               ^
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h:173:7: error: ‘archive_input_seq’ is not a member of ‘boost::serialization::stl’
       boost::serialization::stl::archive_input_seq<Archive, QList<U> >,
       ^
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h:173:59: error: expected primary-expression before ‘,’ token
       boost::serialization::stl::archive_input_seq<Archive, QList<U> >,
                                                           ^
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h:173:70: error: expected primary-expression before ‘>’ token
       boost::serialization::stl::archive_input_seq<Archive, QList<U> >,
                                                                      ^
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h:173:71: error: expected primary-expression before ‘,’ token
       boost::serialization::stl::archive_input_seq<Archive, QList<U> >,
                                                                       ^
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h:174:7: error: ‘no_reserve_imp’ is not a member of ‘boost::serialization::stl’
       boost::serialization::stl::no_reserve_imp< QList<U> > >(ar, t);
       ^
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h:174:59: error: expected primary-expression before ‘>’ token
       boost::serialization::stl::no_reserve_imp< QList<U> > >(ar, t);
                                                           ^
/builddir/build/BUILD/IQmol-df94cf68b9d9d813e4d781c7edb9ac638724dadf/src/Data/Serialization.h:174:61: error: expected primary-expression before ‘>’ token
       boost::serialization::stl::no_reserve_imp< QList<U> > >(ar, t);
                                                             ^
</pre>

**Comment by nutjunkie** [comment]
I don't understand why load_collection has been deprecated, especially since save_collection still seems to exist.  The work-around at the moment is to use Boost 1.56, which has both defined.

**Comment by jwakely** [comment]
It seems that you are relying on internals of Boost.Serialization that are not part of the public API and so have changed in the 1.58.0 release. A different approach (but apparently still using non-public interfaces) is shown in https://github.com/boostorg/property_tree/commit/52a99b57d4636d9cedce7f79ecdb668976feb89e
